"""empty message

Revision ID: 0135f0c6ca44
Revises: 7470bc6e4e8d
Create Date: 2025-06-13 07:15:44.059012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0135f0c6ca44'
down_revision = '7470bc6e4e8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('fecha_actualizacion')

    # ### end Alembic commands ###
