"""Initial migration for User table with all fields

Revision ID: 7470bc6e4e8d
Revises: 
Create Date: 2025-06-12 19:45:59.589698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7470bc6e4e8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('primer_apellido', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('segundo_apellido', sa.String(length=100), nullable=True),
    sa.Column('telefono_emergencia', sa.String(length=20), nullable=True),
    sa.Column('nombre_emergencia', sa.String(length=100), nullable=True),
    sa.Column('empresa', sa.String(length=100), nullable=True),
    sa.Column('cedula', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('actividad', sa.String(length=50), nullable=True),
    sa.Column('capacidad', sa.String(length=50), nullable=True),
    sa.Column('participacion', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
