"""Add additional user contact and medical fields

Revision ID: f849df7bc2ea
Revises: 0135f0c6ca44
Create Date: 2025-06-13 12:59:39.529337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f849df7bc2ea'
down_revision = '0135f0c6ca44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_cumpleanos', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('tipo_sangre', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('poliza', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('aseguradora', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('alergias', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('enfermedades_cronicas', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('enfermedades_cronicas')
        batch_op.drop_column('alergias')
        batch_op.drop_column('aseguradora')
        batch_op.drop_column('poliza')
        batch_op.drop_column('tipo_sangre')
        batch_op.drop_column('fecha_cumpleanos')

    # ### end Alembic commands ###
